window.ReadSpeakerDefer={deferred:null,clickhandler:function(b){b=b||window.event;var d=b.target||b.srcElement;3===d.nodeType&&(d=d.parentNode);if(d!==document&&window.ReadSpeakerDefer.isRSLink(d)){window.ReadSpeakerDefer.deferred=d;(d=window.ReadSpeakerDefer.findRSParent(d))&&d.className&&!/rsdeferred/i.test(d.className)&&(d.className+=" rsdeferred");if(window.ReadSpeakerJIT){d=window.rspkr;if(/ios|ipad|iphone|ipod|android/i.test(window.navigator.userAgent)&&(d.audio=new Audio,d=d.audio.play(),void 0!==
d))d.then(function(){})["catch"](function(b){rspkr.log(b)});window.rspkr.loadCore()}b.cancelBubble=!0;b.preventDefault&&b.preventDefault();b.stopPropagation&&b.stopPropagation();return!1}},init:function(){this.RSDeferClick(document)},isRSLink:function(b){return this.isRSParent(b.parentNode)||b.href&&-1<b.href.indexOf("readspeaker.com/cgi-bin/rsent")},isRSParent:function(b){return b?b.getAttribute("class")&&-1<b.getAttribute("class").indexOf("rsbtn")||b.id&&"string"===typeof b.id&&-1<b.id.indexOf("readspeaker_button"):
!1},findRSParent:function(b){for(;b.parentNode&&b.parentNode!==document&&(b=b.parentNode,"a"!=b.tagName.toLowerCase()||!this.isRSLink(b)););return b==document?void 0:b.parentNode},RSDeferClick:function(b){b.addEventListener?b.addEventListener("click",this.clickhandler,!1):b.attachEvent?b.attachEvent("onclick",this.clickhandler):b.onclick=this.clickhandler}};window.ReadSpeakerDefer.init();
(function(b){var d,h={major:"2",minor:"5",update:"12",revision:"5310",prod:"embhl"},m=[],J=0,w=0,K=!1,x=[],L=0,n=[],M=!1,y=!1,T=0,C=!1,p=null,k="default",N=!1,z=[],O=!1,D="",E={},F=!1,G="",A=null,s=!1,H=function(a){if("string"==typeof a){a="ReadSpeaker."+a.replace("_",".");a=a.split(".");for(var f=b,c=0,d=a.length;c<d;c++)if(f)if(f[a[c]]){if(c==d-1)return f[a[c]];f=f[a[c]]}else break;else break;return!1}},Q=function(a,f){x.push(a);L++;f=f||[a];for(var c=0,d=f.length;c<d;c++)try{var e=H(f[c]);"function"==
typeof e.init&&e.init.apply(e,[])}catch(U){u("[rspkr] Could not load: "+f[c]+" | "+U,3)}L===w&&!0===K&&(u("[rspkr] All prod mods loaded. _domready = "+C,4),s&&b.ReadSpeaker.init(),c=function(){rspkr.Common.createShortcuts();rspkr.devt("onModsLoaded",b);rspkr.devt("onAfterModsLoaded",b);E.onAdapterReady?rspkr.devt("onReady",b):rspkr.evt("onAdapterReady",function(){rspkr.devt("onReady",b)});b.ReadSpeaker.ui.viewport={width:$rs.width(b),height:$rs.height(b)}},b.ReadSpeaker.Common.addEvent("onReady",
function(){P.executeCode();P.flush();if(A)a:{rspkr.log("[rspkr.startAutoplay] Id: "+A);var a=$rs.get(A);if($rs.isArray(a)&&0<a.length)a=a[0];else if($rs.isArray(a)&&0==a.length)break a;a=$rs.findIn(a,"a");if($rs.isArray(a)&&0<a.length)a=a[0];else if($rs.isArray(a)&&0==a.length)break a;b.readpage(a)}}),C?c():b.ReadSpeaker.Common.addEvent("onDOMReady",c))},R=function(){if(!y){s&&!F&&(document.getElementById("rsmod_Styles").href=G+"ReadSpeaker.Styles.css");for(var a in m)m.hasOwnProperty(a)&&(mod=a,
r.load({id:"req_"+mod,type:"text/javascript",src:"ReadSpeaker."+mod+".js",cb:function(){var a=(b.event&&b.event.srcElement&&b.event.srcElement.id?b.event.srcElement.id:this.id).replace("req_",""),a=a.replace("_","."),a=!1===m[a]?[a]:m[a],c;J++;for(var d=0,e=a.length;d<e;d++)x.push(a[d]),c=H(a[d]),"function"==typeof c.init&&c.init.apply(c,[]);J===Object.size(m)&&(b.ReadSpeaker.Common.addEvent("onModsLoaded",b.ReadSpeaker.pub.Config.setup),O=!0,a={id:"",type:"text/javascript",src:"",cb:function(){var a=
(b.event&&b.event.srcElement&&b.event.srcElement.id?b.event.srcElement.id:this.id).replace("rsmod_","");x.push(a);a=H(a);"function"==typeof a.init&&a.init.apply(a,[]);if(O&&b.ReadSpeaker.modmap&&!M){for(var a=b.ReadSpeaker.modmap,c=[],d=0,f="|",q=[],e=0,h=z.length;e<h;e++)if(c=a.products&&"function"==typeof a.products[z[e]]?a.products[z[e]]():null){for(var g=d=0,k=c.length;g<k;g++)-1===f.indexOf("|"+c[g][0]+c[g][1]+"|")&&(c[g][0].length&&(q[c[g][0]]=c[g][2],r.load({id:"rsmod_"+c[g][0],type:c[g][1],
src:"ReadSpeaker."+c[g][0]+("text/css"===c[g][1]?".css":".js"),cb:function(){var a=(b.event&&b.event.srcElement&&b.event.srcElement.id?b.event.srcElement.id:this.id).replace("rsmod_","");Q(a,q[a])},async:!0})),"undefined"!==typeof c[g][1]&&/text\/javascript/.test(c[g][1])&&d++,f+=c[g][0]+c[g][1]+"|");w+=d}K=!0}}},c=b.ReadSpeaker.lib.Facade.currentLib().toLowerCase(),"rslib"==c?(a.id="rsmod_lib.RSLib",a.src="ReadSpeaker.lib.RSLib.js"):(a.id="rsmod_lib.Facade.adapter."+c,a.src="ReadSpeaker.lib.Facade.adapter."+
c+".js"),r.load(a))},async:!0}))}},S=function(){rspkr.log("[rspkr.updateBaseClass] Attempting to update..");for(var a=document.getElementsByTagName("div"),d=/\brsbtn\b/,c=0,q=a.length;c<q;c++)d.test(a[c].className)&&(a[c].className=a[c].className.replace(d,b.rsConf.ui.rsbtnClass));rspkr.log("[rspkr.updateBaseClass] Update successful!");Q("skinfile")};d={extract:function(a){if("string"==typeof a){var b={};a=a.split(/[;&]/);for(var c,d=0;d<a.length;d++)(c=a[d].split("="))&&2==c.length&&(b[unescape(c[0])]=
unescape(c[1]).replace(/\+/g," "));return b}return{}}};var P={isok:!0,executeCode:function(){this.isok=!0;if(!n.length)return!0;for(idx in n)if(n.hasOwnProperty(idx)&&"function"==typeof n[idx])try{n[idx].apply(b,[])}catch(a){this.isok=!1,rspkr.log("[rspkr.q] "+a,3)}},flush:function(){n=[]}},r={load:function(a){if("text/javascript"==a.type||"text/css"==a.type){a.src=p.path+a.src;var d=document.getElementsByTagName("head")[0],c=document.createElement("text/javascript"==a.type?"script":"link"),q=[h.major,
h.minor,h.update,h.revision].join(".");"function"==typeof a.cb&&(void 0!==c.onreadystatechange?c.onreadystatechange=function(){"complete"!=this.readyState&&"loaded"!=this.readyState||a.cb.apply(b)}:c.onload=a.cb);c.id=a.id.replace(".","_");c.type=a.type;"text/javascript"==a.type?(c.src=a.src+"?v="+q,a.async&&(c.async=!0)):(c.rel="stylesheet",c.href=a.src+"?v="+q);d.appendChild(c)}}},V=0,I={1:[],2:[],3:[],4:[],5:[],6:[]},t={1:{lbl:"Info",method:"log"},2:{lbl:"Warn",method:"warn"},3:{lbl:"Err",method:"error"},
4:{lbl:"AS",method:"log"},5:{lbl:"SW",method:"log"}},u=function(a,b){var c=D;b=b||1;I[b].push(a);if(c&&"string"===typeof c&&-1<c.indexOf(","+b+",")){c=t[b].lbl;try{console[t[b].method]&&console[t[b].method](V++ +". "+c+": "+a)}catch(d){}}},W=function(a){D=/^,[0-9,]*,$/.test(a)?a:","+a+","};Object.size=function(a){var b=0,c;for(c in a)a.hasOwnProperty(c)&&b++;return b};if(b.rsConf&&b.rsConf.params&&"string"===typeof b.rsConf.params&&b.rsConf.params)var v=b.rsConf.params,l=v.split("?");else l=document.getElementsByTagName("script"),
v=l[l.length-1].getAttribute("src"),l=v.split("?");if(/\?/i.test(v)&&1<l.length&&l[1].length){var G=v.replace(/[^\/]*$/,""),B;if(/rsdebug=rsdebug/i.test(document.location.href))try{B=","+document.location.href.split("?").pop().match(/rsdebug=rsdebug([^$|&]*)/i).pop()+","}catch(X){B=",3,"}else B="";D=B;p=d=d.extract(l[1]);k=d.skin||"default";z=d.pids.split(",");p.path=l[0].replace("ReadSpeaker.js","");m.Core=["Common","lib.Facade","modmap"];m["pub.Config"]=!1;A=d.autoplay;s=b.ReadSpeakerJIT="1"===
d.jit;p.forceBasicMode&&"1"===p.forceBasicMode||document.attachEvent&&/MSIE/i.test(navigator.userAgent)&&(document.compatMode&&"backcompat"===document.compatMode.toLowerCase()||/MSIE 6\./i.test(navigator.userAgent))?(F=!0,r.load({id:"rsmod_Styles",type:"text/css",src:(p.skinPathBasic||"ReadSpeaker.Styles-Basic")+".css",cb:null})):(r.load({id:"rsmod_Styles",type:"text/css",src:"ReadSpeaker.Styles"+(s?"-Button":"")+".css",cb:null}),"default"!==k&&!s&&(w++,r.load({id:"rsskin_"+k+"_style",type:"text/css",
src:"skins/"+k+"/"+k+".css",cb:null}),r.load({id:"rsskin_"+k+"_js",type:"text/javascript",src:"skins/"+k+"/"+k+".js",cb:function(){"default"!==k&&y?S():N=!0},async:!0})));s||R()}else M=!0;d=new function(){this.meta={obj:h,version:[h.major,h.minor,h.update].join(".")+"_rev"+h.revision+"-"+h.prod};this.q=function(a){"function"==typeof a&&(E.onReady?a.apply(b,[]):n.push(a))};this.init=function(){y||(y=!0,document.addEventListener&&document.removeEventListener("DOMContentLoaded",b.ReadSpeaker.init,!1),
C=!0,b.ReadSpeaker.Common&&b.ReadSpeaker.Common.dispatchEvent("onDOMReady"),u("[rspkr] DOM Ready!"),N&&(u("[rspkr] Updating base class.",1),S()))};this.getLoadedMods=function(){return x};this.rsidCount=1E3;this.logcount=0;this.log=function(a,b){u(a,b||1)};this.showLog=function(a){a=a||"1";rspkr.log("[rspkr.printErrorLog]",1);a=(a||"3").split(",");for(var b=0;b<a.length;b++)if(I.hasOwnProperty(a[b])){var c=I[a[b]],d=a[b],d=parseInt(d)||3,e=t[d].lbl;console.groupCollapsed&&console.groupCollapsed(e);
for(e=0;e<c.length;e++)try{console[t[d].method]&&console[t[d].method](c[e])}catch(h){}console.groupCollapsed&&console.groupEnd()}};this.getID=function(){return"readspeaker"+T++};this.getVersion=function(){return this.meta.version};this.skin=k;this.displog=E;this.basicMode=F;this.params=p;this.setDebugLevel=W;this.baseUrl=G;this.loadCore=R;this.audio=null};b.ReadSpeaker=b.rs=b.rspkr=d})(window);ReadSpeaker.enums={mime:{tjs:"text/javascript",tcss:"text/css",thtml:"text/html"}};
(function(b){if(!window.ReadSpeakerJIT){var d=navigator.userAgent;/mozilla/i.test(d)&&!/(compati)/.test(d)||/opera/i.test(d)||/webkit/i.test(d)?document.addEventListener("DOMContentLoaded",b,!1):window.onload=b}})(ReadSpeaker.init);
